browser = chrome
name = Sanzhar
base.url=https://www.automationexercise.com/
gorest.base.url = https://gorest.co.in
bearer.token = b1f821e740f573e8500ae6da6cdfd6679c09e19d8a08cda03dfb6546dd893d8e
server = localhost
port = 5432
user = postgres